 version: "3.9"

 services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - backend

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    restart: unless-stopped

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      redis:
        condition: service_healthy

    ports:
      - "8000:8000"

    networks:
      - backend

  worker:
    build: ./worker
    restart: unless-stopped

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - backend

  frontend:
    build: ./frontend
    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    ports:
      - "3000:3000"

    networks:
      - backend

 networks:
  backend:  